apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:                                  # gcpsm provider
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret              # secret name containing SA key
            key: secret-access-credentials  # key name containing SA key
      projectID: kubernetes-thao               # name of Google Cloud project