apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-demo
  namespace: argocd-demo
spec:
  project: default
  source:
    repoURL: https://github.com/lvthao/k8s-doc.git
    targetRevision: HEAD
    path: example/wordpress/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
    